if(WORKING_DIRECTORY STREQUAL "")
  string(RANDOM LENGTH 16 ALPHABET abcdef0123456789 suffix)
  set(temporary_root "$ENV{TMPDIR}")
  if(temporary_root STREQUAL "")
    set(temporary_root "$ENV{TEMP}")
  endif()
  if(temporary_root STREQUAL "")
    set(temporary_root "$ENV{TMP}")
  endif()
  cmake_path(IS_PREFIX PROJECT_ROOT "${temporary_root}" NORMALIZE inside_project)
  if(CASE STREQUAL "info-missing" AND
      (temporary_root STREQUAL "" OR inside_project))
    if(WIN32)
      if(NOT "$ENV{LOCALAPPDATA}" STREQUAL "")
        set(temporary_root "$ENV{LOCALAPPDATA}/Temp")
      elseif(NOT "$ENV{USERPROFILE}" STREQUAL "")
        set(temporary_root "$ENV{USERPROFILE}/AppData/Local/Temp")
      else()
        message(FATAL_ERROR "Cannot locate a temporary directory outside the project")
      endif()
    else()
      set(temporary_root "/tmp")
    endif()
  endif()
  if(temporary_root STREQUAL "")
    set(temporary_root "${CMAKE_CURRENT_BINARY_DIR}")
  endif()
  set(temporary_directory "${temporary_root}/cxxp-cli-${suffix}")
  file(MAKE_DIRECTORY "${temporary_directory}")
  set(WORKING_DIRECTORY "${temporary_directory}")
endif()
set(arguments)
if(CASE STREQUAL "help")
  set(arguments --help)
elseif(CASE STREQUAL "info")
  set(arguments info)
elseif(CASE STREQUAL "info-help")
  set(arguments info --help)
elseif(CASE STREQUAL "info-missing")
  set(arguments info)
elseif(CASE STREQUAL "version")
  set(arguments --version)
elseif(CASE STREQUAL "unknown")
  set(arguments --help --unknown)
elseif(CASE STREQUAL "extra")
  set(arguments --help --version)
endif()

execute_process(COMMAND "${EXECUTABLE}" ${arguments}
  WORKING_DIRECTORY "${WORKING_DIRECTORY}"
  RESULT_VARIABLE status OUTPUT_VARIABLE output ERROR_VARIABLE error)
if(DEFINED temporary_directory)
  file(REMOVE_RECURSE "${temporary_directory}")
endif()

if(CASE STREQUAL "unknown" OR CASE STREQUAL "extra" OR
    CASE STREQUAL "info-missing")
  if(NOT status STREQUAL "1" OR NOT output STREQUAL "")
    message(FATAL_ERROR "Expected exit 1 and empty stdout: ${status}; ${output}")
  endif()
  if(CASE STREQUAL "info-missing")
    set(diagnostic "no cxx.json found")
  elseif(CASE STREQUAL "unknown")
    set(diagnostic "unknown argument '--unknown'")
  else()
    set(diagnostic "expected a single option")
  endif()
  if(NOT error MATCHES "${diagnostic}" OR
      (NOT CASE STREQUAL "info-missing" AND NOT error MATCHES "Usage: cxxp"))
    message(FATAL_ERROR "Missing diagnostic or usage: ${error}")
  endif()
elseif(CASE STREQUAL "info")
  if(NOT status STREQUAL "0" OR NOT error STREQUAL "")
    message(FATAL_ERROR "Expected info success: ${status}; ${error}")
  endif()
  string(JSON output_version ERROR_VARIABLE json_error GET "${output}" outputVersion)
  if(NOT json_error STREQUAL "NOTFOUND" OR NOT output_version EQUAL 1)
    message(FATAL_ERROR "Unexpected info JSON: ${json_error}; ${output}")
  endif()
  string(JSON project_file ERROR_VARIABLE json_error GET "${output}" projectFile)
  if(NOT json_error STREQUAL "NOTFOUND" OR NOT project_file STREQUAL "cxx.json")
    message(FATAL_ERROR "Unexpected project file: ${json_error}; ${output}")
  endif()
  execute_process(COMMAND "${EXECUTABLE}" info
    WORKING_DIRECTORY "${PROJECT_ROOT}"
    RESULT_VARIABLE root_status OUTPUT_VARIABLE root_output
    ERROR_VARIABLE root_error)
  if(NOT root_status STREQUAL "0" OR NOT root_error STREQUAL "" OR
      NOT output STREQUAL root_output)
    message(FATAL_ERROR "Root and nested info output differ")
  endif()
elseif(CASE STREQUAL "info-help")
  if(NOT status STREQUAL "0" OR NOT error STREQUAL "" OR
      NOT output MATCHES "Usage: cxxp info" OR
      NOT output MATCHES "nearest cxx.json" OR
      NOT output MATCHES "source and header files" OR
      NOT output MATCHES "no timestamps or tool versions" OR
      NOT output MATCHES "cxxp command reference")
    message(FATAL_ERROR "Unexpected info help: ${status}; ${output}; ${error}")
  endif()
else()
  if(NOT status STREQUAL "0" OR NOT error STREQUAL "")
    message(FATAL_ERROR "Expected success and empty stderr: ${status}; ${error}")
  endif()
  if(CASE STREQUAL "version")
    if(NOT output STREQUAL "cxxp ${VERSION}\n")
      message(FATAL_ERROR "Unexpected version: ${output}")
    endif()
  elseif(NOT output MATCHES "Usage: cxxp" OR
      NOT output MATCHES "--help" OR NOT output MATCHES "--version" OR
      NOT output MATCHES "Commands:" OR NOT output MATCHES "info --help")
    message(FATAL_ERROR "Incomplete help: ${output}")
  endif()
endif()
