if(WORKING_DIRECTORY STREQUAL "")
  set(temporary_root "$ENV{TMPDIR}")
  if(temporary_root STREQUAL "")
    if(WIN32)
      set(temporary_root "$ENV{TEMP}")
    else()
      set(temporary_root /tmp)
    endif()
  endif()
  string(RANDOM LENGTH 16 ALPHABET abcdef0123456789 suffix)
  set(temporary_directory "${temporary_root}/cxxp-cli-${suffix}")
  file(MAKE_DIRECTORY "${temporary_directory}")
  set(WORKING_DIRECTORY "${temporary_directory}")
endif()
set(arguments)
if(CASE STREQUAL "help")
  set(arguments --help)
elseif(CASE STREQUAL "version")
  set(arguments --version)
elseif(CASE STREQUAL "unknown")
  set(arguments --help --unknown)
elseif(CASE STREQUAL "extra")
  set(arguments --help --version)
endif()

execute_process(COMMAND "${EXECUTABLE}" ${arguments}
  WORKING_DIRECTORY "${WORKING_DIRECTORY}"
  RESULT_VARIABLE status OUTPUT_VARIABLE output ERROR_VARIABLE error)
if(DEFINED temporary_directory)
  file(REMOVE_RECURSE "${temporary_directory}")
endif()

if(CASE STREQUAL "unknown" OR CASE STREQUAL "extra")
  if(NOT status STREQUAL "1" OR NOT output STREQUAL "")
    message(FATAL_ERROR "Expected exit 1 and empty stdout: ${status}; ${output}")
  endif()
  if(CASE STREQUAL "unknown")
    set(diagnostic "unknown argument '--unknown'")
  else()
    set(diagnostic "expected a single option")
  endif()
  if(NOT error MATCHES "${diagnostic}" OR NOT error MATCHES "Usage: cxxp")
    message(FATAL_ERROR "Missing diagnostic or usage: ${error}")
  endif()
else()
  if(NOT status STREQUAL "0" OR NOT error STREQUAL "")
    message(FATAL_ERROR "Expected success and empty stderr: ${status}; ${error}")
  endif()
  if(CASE STREQUAL "version")
    if(NOT output STREQUAL "cxxp ${VERSION}\n")
      message(FATAL_ERROR "Unexpected version: ${output}")
    endif()
  elseif(NOT output MATCHES "Usage: cxxp" OR
      NOT output MATCHES "--help" OR NOT output MATCHES "--version")
    message(FATAL_ERROR "Incomplete help: ${output}")
  endif()
endif()
